name: FingerprintDecoder
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1m=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - beautifulsoup4==4.10.0
    - charset-normalizer==2.0.10
    - filelock==3.4.2
    - fonttools==4.29.0
    - gdown==4.2.0
    - idna==3.3
    - matplotlib==3.5.1
    - pillow==9.0.0
    - pysocks==1.7.1
    - pytz==2021.3
    - requests==2.27.1
    - six==1.16.0
    - soupsieve==2.3.1
    - urllib3==1.26.8
prefix: /home/islambek/anaconda3/envs/FingerprintDecoder
